Repository Purple-Stock/open-erp, pull requests merged in 2023-11, with the labels that each got.

#345 Feat/337 red alert for pending orders
  Gemfile
  Gemfile.lock
  app/controllers/home_controller.rb
  app/views/home/_order_items.html.erb
  app/views/home/index.html.erb
Labels: enhancement

#348 Feat/313 count zero order items
  app/helpers/home_helper.rb
  app/views/home/_order_items.html.erb
Labels: bling

#349 Staging
  app/helpers/home_helper.rb
  app/views/home/_order_items.html.erb
Labels: bling

#331 [#319] Add helper to group order items
  app/controllers/home_controller.rb
  app/models/bling_order_item.rb
  app/views/home/_order_items.html.erb
  app/views/home/index.html.erb
  spec/models/bling_order_item_spec.rb
Labels: bling

#350 feat index.html.erb: task 339
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
Labels: enhancement, bling

#353 Feat/338 order history quantity
  app/controllers/bling_order_item_histories_controller.rb
  app/helpers/bling_order_item_histories_helper.rb
  app/javascript/vendors/stisla/scripts.js
  app/models/bling_order_item.rb
  app/presenters/bling_order_item_histories_presenter.rb
  app/views/bling_order_item_histories/index.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_sidebar.html.erb
  config/routes.rb
  package-lock.json
  package.json
  spec/factories/bling_order_items.rb
  spec/helpers/bling_order_item_histories_helper_spec.rb
  spec/models/bling_order_item_spec.rb
  spec/presenters/bling_order_item_histories_presenter_spec.rb
  spec/requests/bling_order_item_histories_spec.rb
  spec/views/bling_order_item_histories/index.html.erb_spec.rb
  yarn.lock
Labels: bling

#359 feat bling_order_item_histories/index.html.erb: task #358
  app/views/bling_order_item_histories/index.html.erb
Labels: enhancement
